name: Sample application
on: workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Maven checkstyle
        run: mvn checkstyle:checkstyle

  Build_And_Publish:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Build and Upload image to ECR 
        uses: appleboy/docker-ecr-action@master
        with:
        access_key: ${{ secrets.aws_access_key_id }}
        secret_key: ${{ secrets.aws_secret_access_key }}
        registry: ${{ secrets.registry }}
        repo: sample-ecr-repo
        region: us-east-1
        auto_tag: true
        daemon_off: false
        dockerfile: ./Dockerfile
        context: ./
